# Generated by Django 6.0.2 on 2026-02-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratinghistory',
            name='speed_bonus',
        ),
        migrations.RemoveField(
            model_name='ratinghistory',
            name='streak_multiplier',
        ),
        migrations.AddField(
            model_name='ratinghistory',
            name='estimated_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ratinghistory',
            name='multiplier',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='ratinghistory',
            name='time_spent_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ratinghistory',
            name='earned_points',
            field=models.FloatField(default=0),
        ),
    ]
