# Generated by Django 6.0.2 on 2026-03-01 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_remove_ratinghistory_speed_bonus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrating',
            old_name='streak_days',
            new_name='current_streak',
        ),
    ]
