# Generated by Django 6.0.2 on 2026-03-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_rename_streak_days_userrating_current_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='current_streak',
            field=models.IntegerField(default=2),
        ),
    ]
