# Generated by Django 6.0.2 on 2026-03-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_alter_userrating_current_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='last_penalty_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
