# Generated by Django 6.0.2 on 2026-03-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_userrating_last_penalty_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='current_streak',
            field=models.IntegerField(default=1),
        ),
    ]
