# Generated by Django 6.0.2 on 2026-02-22 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True, verbose_name='ID для коду')),
                ('price', models.IntegerField(default=10, verbose_name='Ціна')),
                ('slot', models.CharField(choices=[('mouth', 'Рот'), ('eyes_l', 'Ліве око'), ('eyes_r', 'Праве око'), ('head_top', 'Верх голови (волосся/шапки)'), ('torso', 'Тіло'), ('legs_l', 'Ліва нога'), ('legs_r', 'Права нога'), ('arms_l', 'Ліва рука'), ('arms_r', 'Права рука'), ('feet', 'Взуття'), ('none', 'Без слота (аксесуари)')], default='none', max_length=20, verbose_name='Слот')),
                ('css_id', models.CharField(help_text='Напр: part-smile', max_length=50, verbose_name='CSS ID в шаблоні')),
            ],
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equipped', models.BooleanField(default=False, verbose_name='Одягнено зараз')),
                ('is_owned', models.BooleanField(default=False, verbose_name='Придбано')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Інвентар користувача',
                'verbose_name_plural': 'Інвентар користувачів',
                'unique_together': {('user', 'item')},
            },
        ),
    ]
