# Generated by Django 6.0.2 on 2026-02-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinventory',
            options={'verbose_name': 'Предмет користувача', 'verbose_name_plural': 'Інвентар'},
        ),
        migrations.RemoveField(
            model_name='userinventory',
            name='is_owned',
        ),
        migrations.AddField(
            model_name='item',
            name='icon',
            field=models.CharField(default='📦', max_length=10, verbose_name='Іконка (emoji)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='css_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CSS ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='ID для коду (slug)'),
        ),
    ]
