# Generated by Django 6.0.2 on 2026-02-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(default='16:00'),
        ),
    ]
