# Generated by Django 6.0.2 on 2026-02-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(default='23:59'),
        ),
    ]
