# Generated by Django 6.0.2 on 2026-02-28 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_deadline_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='planned_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
